name: MIGRIS slots-check Bot CI
on:

  schedule:
    - cron: '30 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'npm'
      - name: Install NPM packages
        run: npm ci
      - name: Run Bot
        run: npm run bot
        env:
          EMAIL_OF_RECEIVER: ${{ secrets.EMAIL_OF_RECEIVER }}
          EMAIL_OF_SENDER: ${{ secrets.EMAIL_OF_SENDER }}
          API_KEY: ${{ secrets.API_KEY }}
